# Generated by Django 5.1.7 on 2026-02-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, choices=[('ARS', 'ARS'), ('USD', 'USD')], max_length=3, null=True)),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=3)),
            ],
        ),
    ]
